level: [2, 4, 6, 8, 10]

recto: [" 😯", " 😀", " 😁", " 🤣", " 😉",
        " 😎", " 😍", " 🤗", " 🤩", " 😑",
        " 🙄", " 😣", " 😏", " 😮", " 🤐",
        " 😫", " 😴", " 😛", " 🤤", " 😓",
        " 🙃", " 🤑", " 🥵", " 🥶", " 😤",
        " 😭", " 🥳", " 😨", " 🤯", " 😱",
        " 🤪", " 😵", " 😡", " 🥺", " 😷",
        " 🤕", " 🤢", " 🤮", " 😇", " 🤠",
        " 🤥", " 🧐", " 😈", " 🤡", " 👻",
        " 🤘", " 🐍", " 🦆", " 🦁", " 🎮"]

verso : "❓"